### ISSUE TITLE
Cypher query fails without an error message

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Plater#105]
When I try the following Cypher query on , I get a blank error message:

```
{
  "query": "MATCH (s)-[p]-(o) WHERE 'http://model.geneontology.org/5323da1800000002' IN p.xref RETURN DISTINCT s, p, o, TYPE(p) AS pred_type, CASE    WHEN startNode(p) = s THEN ''    WHEN endNode(p) = s THEN 'reverse'    ELSE ''  END AS direction;"
}
```

Here's the response:

```
{
  "error": ""
}
```

If I add a `LIMIT 10` or `LIMIT 100`, the query works, but increasing it to `LIMIT 1000` causes it to fail again.

@EvanDietzMorris tells me that the error visible in the server logs:

```
neo4j.exceptions.DatabaseError: {code: Neo.DatabaseError.Statement.ExecutionFailed} {message: Index 104 out of bounds for length 8}
```

This used to work before the Neo4J 4->5 upgrade, so it's probably related to that somehow. I think there are two issues here:
- [ ] It should return an/the error message in `error`.
- [ ] This query should work again.

**Comment by EvanDietzMorris** [comment]
We found that this was actually due to a corrupted neo4j instance and not Plater. Error messaging was improved.
