### ISSUE TITLE
ICEES KG endpoint example queries not compatible with ICEES

### ISSUE THREAD

**Issue by karafecho** [TranslatorSRI/Plater#73]
This issue is to report that several of the example queries for ICEES KG will return errors or empty results because they are not compatible with the underlying data.

For example, for the 'query reasoner via one of several inputs' functionality, the example query includes a MONDO identifier that ICEES KG does not support. I think this should be changed from MONDO:0004969 to MONDO:0004979. Likewise, the category for n0 should be changed from biolink:Gene to biolink:ChemicalEntity. These changes provide a successful query `biolink:ChemicalEntity related_to biolink:Disease (MONDO:0004979)`.

The example query for the overlay endpoint returns an error. I think this might be similar to the above example in that I don't think the example query is something that ICEES KG can respond to.

With the meta KG endpoint, the identifier prefixes associated with Biolink categories appear to differ from those that ICEES KG actually uses. For instance,
```
    "biolink:SmallMolecule": {
      "id_prefixes": [
        "PUBCHEM.COMPOUND",
        "UNII",
        "CHEBI"
```
does not include RXNORMCUI, but the drugs included in ICEES KG are actually mapped to RXNORMCUI not PUBCHEM.COMPOUND, UNII, or CHEBI. I think the issue has to do with the fact that the identifier prefixes are being pulled automatically from Plater/Automat, but I'm wondering if this will be problematic.

Assigning @cbizon because I do not know who the point person is for Plater-related issues.

**Comment by cbizon** [comment]
@YaphetKG is it possible to customize the example queries per-plater instance?  All of the ones on the automat site use this same disease to chemical entity query, even though it's not really a valid query for most of them.

Also, is it the case that the prefixes in meta_knowledge_graph are built from the data?  Or does plater make assumptions about what the data ought to look like?

**Comment by YaphetKG** [comment]
Hi @cbizon , @karafecho 
For the example query i think we can replace the example on deployment by mounting a custom json inplace of the default file. That way we can customize each instance with no code change to the repo.

As for prefixes , meta_kg is built from the data (https://github.com/TranslatorSRI/Plater/blob/09ac8600cf09b646b91b46252b79c30d529347a2/PLATER/services/util/graph_adapter.py#L429) this function is responsible for doing so. We don't do any filtering and the raw prefixes on the nodes.  

I checked the ICEES neo4j for nodes that have that curie listed in their id as well as equivalent ids 
```
match (c) where any (x in c.equivalent_identifiers where x starts with 'RXNORMCUI') return c limit 1
```
but there seems to be no result. Could be the data is something different(?)

**Comment by karafecho** [comment]
Thanks for investigating, Yaphet. 

Please let me know if you need anything from me to address the example queries.

WRT the meta KG prefixes, I'm confused. I had initially brought the issue to Max's attention, but he thought it was a Plater issue. @maximusunc, any insights?

**Comment by karafecho** [comment]
@YaphetKG @cbizon : So, Max reminded me that the current issue reflects a decision I made a while back. In short, Max, Hong, and I have been refactoring ICEES into two separate services: ICEES (fully featured, dynamic, non-TRAPI) and ICEES KG (limited in features, static, TRAPI). As part of that effort, we've been working to more fully automate and improve the various mapping steps, which had been introducing a lot of noise and incorrect mappings. The new process begins with a file that I manually created and that is leveraged for various downstream mapping and enumeration steps. The mapping of ICEES feature variables to Biolink prefixes/CURIES is based on `search_term` entries and `limit` parameters that I provided and that are used to programmatically call Name Resolver to retrieve Biolink CURIES for each variable. I tested the approach extensively and was aware of the limitations but felt it was best to harmonize with Translator than to harmonize with FHIR. However, when I looked at the meta KG, I had second doubts.

I'm thinking that we should stick with the current approach, recognizing the limitations but accepting them. Note that there are related GitHub tickets that should eventually address these issues.

RxNorm: Biolink resolved RxNorm issue, moved issue to Node Normalizer, https://github.com/TranslatorSRI/NodeNormalization/issues/127

ICD: open Biolink ticket, https://github.com/biolink/biolink-model/issues/933 

LOINC: open Biolink ticket, https://github.com/biolink/biolink-model/issues/334; will not be a Biolink issue if we adopt LOINC2HPO

**Comment by EvanDietzMorris** [comment]
Example queries are generated based on the SRI testing data file specific to that plater now, so the examples should always be valid.

**Comment by maximusunc** [comment]
Yep, can confirm that the example query for automat icees-kg works. Thanks Evan!

**Comment by karafecho** [comment]
Thanks, all. Looks good now.
