### ISSUE TITLE
CAM Provider KG - new URL

### ISSUE THREAD

**Issue by karafecho** [TranslatorSRI/Plater#97]
This issue is to request that the URL for edge attributes in CAM Provider KG is updated to: https://github.com/NCATSTranslator/Translator-All/wiki/CAM-Provider-KG. I believe the current URL is https://github.com/NCATSTranslator/Translator-All/wiki, which isn't specific to CAM Provider KG.

**Comment by EvanDietzMorris** [comment]
This needed to be done in the infores catalog, it's been done for a little while, closing.

**Comment by karafecho** [comment]
Yes, I took care of the InfoRes / Wiki components; Gaurav fixed the edge attributes. So, we're good.
